config/routes.rb
Rails.application.routes.draw do
  resources :events
  get '/mylife' => 'core_hero#index', as: :index

	get '/mylove' => 'core_hero#mylove', as: :mylove

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/core_hero_controller.rb
class CoreHeroController < ApplicationController
  def index
	@title = "My Life"
  end

  def mylove
	@title = "My Love"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :body, :Lover, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def title

base_title = " My Life"

	if @title.nil
		base_title

	else
		"#{base_title} | #{@title}"

	end
end


end

app/helpers/core_hero_helper.rb
module CoreHeroHelper
		

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/core_hero/index.html.erb
<%= @title %>
<h1>Welcome to my life...</h1>
<p>This app tells eveything about me(Rohit Bhardwaj). My thoughts my knowledge everything I think about... </p>
<p>I would tell you every thing what I want to prove in my life. What I want to achieve in my life... </p>
<p> There are people I care, I would protect them no matter what. </p>

<%= link_to "My Love", :action =>"mylove" %>

app/views/core_hero/mylove.html.erb
<%= @title %>
<h1>Hey You are the sudo user</h1>
<p>You are the one with access privledge that no one has....</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :Lover %><br>
    <%= f.text_field :Lover %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Lover</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.body %></td>
        <td><%= event.Lover %></td>
        <td><%= event.email %></td>
        <td><%= event.password %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @event.body %>
</p>

<p>
  <strong>Lover:</strong>
  <%= @event.Lover %>
</p>

<p>
  <strong>Email:</strong>
  <%= @event.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @event.password %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p> This is my personal App and you are not supposed to read this. But don't worry, I don't mind if you're gonna read It's allright. Just don't judge me. Thanks :) :)
</p>
&copy <%= Time.now.year %>

</footer>

app/views/layouts/_header.html.erb
<header>

Let's play with the idea...
<br><br><br><br><br><br><br><br>
</header>

app/views/layouts/_navigation.html.erb
<nav>
<ul>
	<%= link_to "MyLife", index_path %>
	<%= link_to "MyLove", mylove_path %>
</ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/navigation' %>
<br>
<%= yield %>

<%= render 'layouts/footer' %>



</body>
</html>